defaults:
  run:
    working-directory: eclipse
jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Toolchain JDK
      uses: battila7/jdk-via-jabba@v1
      with:
        javaHomeEnvironmentVariable: TOOLCHAIN_JDK
        jdk: zulu@1.11.0-10
    - continue-on-error: true
      name: Set up Toolchain
      run: "mkdir -p $HOME/.m2 \\\n&& cat << EOF > $HOME/.m2/toolchains.xml\n<?xml\
        \ version=\"1.0\" encoding=\"UTF8\"?>\n<toolchains>\n  <toolchain>\n    <type>jdk</type>\n\
        \      <provides>\n        <version>11</version>\n        <vendor>zulu</vendor>\n\
        \      </provides>\n      <configuration>\n        <jdkHome>${{ env.TOOLCHAIN_JDK\
        \ }}</jdkHome>\n      </configuration>\n  </toolchain>\n</toolchains>\nEOF\n"
      shell: bash
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with Maven
      run: ./mvnw integration-test -B -D"license.skip=true"
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - zulu
        java:
        - 17
        - 21
        os:
        - ubuntu-latest
      max-parallel: 4
name: Eclipse Plugin CI
on:
  repository_dispatch:
    types: trigger-ga___eclipse-ci.yaml
